name = "VectorizationBase"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.21.71"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
LayoutPointers = "10f19ff3-798f-405d-979b-55457f8fc047"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMDTypes = "94e857df-77ce-4151-89e5-788b33177be4"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrayInterface = "0d7ed370-da01-4f52-bd93-41d350b8b718"

[compat]
ArrayInterface = "7"
CPUSummary = "0.1.1 - 0.1.8, 0.1.11, 0.2"
HostCPUFeatures = "0.1"
IfElse = "0.1"
LayoutPointers = "0.1"
Libdl = "1"
LinearAlgebra = "1"
SIMDTypes = "0.1"
Static = "0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1"
StaticArrayInterface = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
