name = "VectorizationBase"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.21.21"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
LayoutPointers = "10f19ff3-798f-405d-979b-55457f8fc047"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SIMDTypes = "94e857df-77ce-4151-89e5-788b33177be4"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
ArrayInterface = "3.1.2 - 3.1.23, 3.1.25"
CPUSummary = "0.1.1"
HostCPUFeatures = "0.1.2"
Hwloc = "2.0"
IfElse = "0.1"
LayoutPointers = "0.1"
SIMDTypes = "0.1"
Static = "0.2, 0.3, 0.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
